stages:
- stage: CI
  jobs:
  - job: CI
    steps:
    - script: docker build -t ${COMPONENT} .
      displayName: Docker Build

- stage: DockerUpload
  condition: succeeded()
  jobs:
  - job: DockerUpload
    steps:
    - script: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 633788536644.dkr.ecr.us-east-1.amazonaws.com
        docker tag ${COMPONENT}:latest 633788536644.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
        docker push 633788536644.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
      displayName: Docker Image Push to ECR
